### ISSUE TITLE
SyntaxError occurs while installing on python3.3

### ISSUE THREAD

**Issue by ponsfoot** [paver/paver#103]
While installing on python3.3, byte-compiling fails due to syntax error as follows:

$ pip install -U Paver -t /tmp/test
Downloading/unpacking Paver
  Running setup.py egg_info for package Paver
    warning: no files found matching '_' under directory 'paver/docs'
Installing collected packages: Paver
  Running setup.py install for Paver
    warning: no files found matching '_' under directory 'paver/docs'
    Installing paver script to /tmp/tmps1kgjz/bin
      File "/tmp/tmps1kgjz/lib/python/paver/deps/path2.py", line 939
        def mkdir(self, mode=0777):
                                ^
    SyntaxError: invalid token

Successfully installed Paver
Cleaning up...

Version:
paver 1.2.0
python 3.3.0

**Comment by NfNitLoop** [comment]
I just got this error after doing a `pip3 install paver`.

This issue has been open for 2.5 years. Does Paver not yet support Python 3?

**Comment by Almad** [comment]
@NfNitLoop It does, but I admit I am underusing it. I thought I've fixed it with soem other things...apparently not. Will look into it.

**Comment by Almad** [comment]
Should be fixed in Python 1.3.
