### ISSUE TITLE
Dependencies not installed when installing Paver project via "python setup.py install"

### ISSUE THREAD

**Issue by smheidrich** [paver/paver#135]
Example **pavement.py** file with dependencies (_plumbum_, for example) declared via "install_requires":

``` python
from paver.setuputils import setup

setup(
name="TEST",
version="0.1",
description="TESTS",
author="Jane Doe",
author_email="none@example.net",
packages=[""],
install_requires=["plumbum"]
)
```

Generate **setup.py** and minilib:

```
$ paver generate_setup
---> paver.misctasks.generate_setup
Write setup.py
$ paver minilib
---> paver.misctasks.minilib
Generate paver-minilib.zip
```

Now try to install it in a virtualenv by invoking `python setup.py install` directly from the project directory:

```
$ mkdir test_venv
$ cd test_venv
$ virtualenv .
Running virtualenv with interpreter /usr/bin/python2
New python executable in ./bin/python2
Also creating executable in ./bin/python
Installing setuptools, pip...done.
$ . bin/activate
$ cd ..
$ python setup.py install
[ output suppressed, looks normal enough though ]
Installed /tmp/pavertest/plumbum-1.4.2-py2.7.egg
[ output suppressed ]
```

As you can see, it does declare that it installed _plumbum_. However, looking at `lib/python2.7/site-packages` inside the virtualenv directory, it isn't there. The corresponding .egg file is present in the project directory, however.

Can anyone reproduce this so far? Am I doing something wrong?

---
## Possible causes

As part of the installation, Paver's [`setuputils._dispatch_setuptools_install`](https://github.com/paver/paver/blob/c66f3183d01185ea877df1502a5aee7d34976f7b/paver/setuputils.py#L44) is called, which in turn calls setuptools' `fetch_build_eggs`.
But this seems to only download the eggs, not install them.

The requirements aren't installed by setuptools' own install command because [those people actually built a mechanism that detects where `install` was called from](https://bitbucket.org/pypa/setuptools/src/6cf39105a5b9/setuptools/command/install.py#cl-63) and does an "old-style" installtion (i.e. the way distutils does it, without installing dependencies) if it wasn't called from inside setuptools itself. I suppose that's why `_dispatch_setuptools_install` was created in the first place; it just doesn't work.

**Comment by Almad** [comment]
@smheidrich Is this still an issue for you?

It unfortunately fell off my radar and now I can see it when doing a cleanup...and the ecosystem moved quite a bit since.

**Comment by Almad** [comment]
I am closing it for now, but please do reopen if still valid. It behaves differently for me: providing a way to reproduce in clean (Docker) environment would be awesome.
