### ISSUE TITLE
paver breaks six

### ISSUE THREAD

**Issue by diogobaeder** [paver/paver#141]
Hi,

When trying to execute a simple attempt to import a module via the `six` module inside a `pavement.py` file, it just fails with an ImportError. To reproduce:

```python
from paver.easy import task


@task
def foo():
    from six.moves import urllib
```
Then just run `paver foo` (with `-f <filename>` if your pavement file has a different name).

If you try to do the same import inside an `ipython` session, however, the import runs just fine, which means it's not a `six` issue, but a `paver` one.

This problem happens both in Python 2 and Python 3 environments.

**Comment by diogobaeder** [comment]
Using the tip version (`-e git+https://github.com/paver/paver.git#egg=Paver`) seems to cut it, the error doesn't exist anymore. It would be nice, however, to have this released.

**Comment by Almad** [comment]
Good point, I'll try to move it forward

**Comment by Almad** [comment]
1.2.4 released

**Comment by diogobaeder** [comment]
Nice! Thanks a lot, Almad! :-)
