### ISSUE TITLE
No release since August 2014

### ISSUE THREAD

**Issue by amorphic** [paver/paver#142]
There hasn't been a new Paver release since 1.2.3 in August 2014. There have been a bunch of commits merged since then and it's a shame that those bugfixes and new features aren't available in production.

Any chance of cutting a new prod release?

**Comment by Almad** [comment]
Fair point; I've been trying to make the changelog better + few more things, but it's better to release at least something.

**Comment by Almad** [comment]
1.2.4 out (hopefully right, not on my default environment and Docker is not out yet), feel free to test.

**Comment by amorphic** [comment]
Wow, thanks for the fast turnaround! :+1:
