### ISSUE TITLE
Can't run paver setup

### ISSUE THREAD

**Issue by flyingcow93** [paver/paver#144]
I have no idea what could be wrong here. I'm on win 7 x64

C:\Users\Brandon>cd C:\Users\Brandon\Dropbox\tba git\the-blue-alliance

C:\Users\Brandon\Dropbox\tba git\the-blue-alliance>paver setup
---> pavement.setup
---> pavement.make
---> pavement.javascript
Combining and Compressing Javascript
python do_compress.py js
Compressing Main JavaScript...
 + static/jwplayer/jwplayer.js
 + static/xcharts/d3.v2.min.js
 + static/xcharts/xcharts.min.js
 + static/javascript/tba_js/tablesorter.js
 + static/javascript/tba_js/tba_charts.js
 + static/javascript/tba_js/tba_countdown.js
 + static/javascript/tba_js/tba_sidebar.js
 + static/javascript/tba_js/tba_typeahead.js
 + static/javascript/tba_js/tba.js
=> static/javascript/tba_combined_js.main.min.js
Original: 303.81 kB
Compressed: 298.35 kB
Reduction: 1.8%

Compressing GameDay JavaScript...
 + static/jwplayer/jwplayer.js
 + static/xcharts/d3.v2.min.js
 + static/xcharts/xcharts.min.js
 + static/javascript/tba_js/tablesorter.js
 + static/javascript/tba_js/tba_charts.js
 + static/javascript/tba_js/tba_countdown.js
 + static/javascript/tba_js/tba_sidebar.js
 + static/javascript/tba_js/tba_typeahead.js
 + static/javascript/tba_js/tba.js
 + static/javascript/tba_js/gameday.js
 + static/javascript/tba_js/gameday_twitter.js
 + static/javascript/tba_js/gameday_matchbar.js
 + static/javascript/tba_js/gameday_ticker.js
 + static/javascript/tba_js/gameday_mytba.js
=> static/javascript/tba_combined_js.gameday.min.js
Original: 342.49 kB
Compressed: 322.41 kB
Reduction: 5.9%

---> pavement.less
Building and Combining CSS
lessc static/css/less_css/tba_style.main.less static/css/less_css/tba_style.main
.css
lessc static/css/less_css/tba_style.gameday.less static/css/less_css/tba_style.g
ameday.css
python do_compress.py css
Compressing Main CSS...
 + static/css/precompiled_css/jquery.fancybox.css
 + static/css/precompiled_css/tablesorter.css
 + static/xcharts/xcharts.min.css
 + static/css/less_css/tba_style.main.css
=> static/css/tba_combined_style.main.min.css
Original: 169.47 kB
Compressed: 134.98 kB
Reduction: 20.4%

Compressing GameDay CSS...
 + static/css/precompiled_css/jquery.fancybox.css
 + static/css/precompiled_css/tablesorter.css
 + static/css/less_css/tba_style.gameday.css
=> static/css/tba_combined_style.gameday.min.css
Original: 173.31 kB
Compressed: 137.32 kB
Reduction: 20.8%

Captured Task Output:
---------------------

---> pavement.setup
---> pavement.make
---> pavement.javascript
python do_compress.py js
---> pavement.less
lessc static/css/less_css/tba_style.main.less static/css/less_css/tba_style.main
.css
lessc static/css/less_css/tba_style.gameday.less static/css/less_css/tba_style.g
ameday.css
python do_compress.py css
Traceback (most recent call last):
  File "E:\Programs\python\lib\site-packages\paver-1.2.4-py2.7.egg\paver\tasks.p
y", line 196, in _run_task
    return do_task()
  File "E:\Programs\python\lib\site-packages\paver-1.2.4-py2.7.egg\paver\tasks.p
y", line 193, in do_task
    return func(**kw)
  File "pavement.py", line 60, in setup
    setup_function()
  File "pavement.py", line 87, in setup_function
    make()
  File "E:\Programs\python\lib\site-packages\paver-1.2.4-py2.7.egg\paver\tasks.p
y", line 321, in __call__
    retval = environment._run_task(self.name, self.needs, self.func)
  File "E:\Programs\python\lib\site-packages\paver-1.2.4-py2.7.egg\paver\tasks.p
y", line 214, in _run_task
    return do_task()
  File "E:\Programs\python\lib\site-packages\paver-1.2.4-py2.7.egg\paver\tasks.p
y", line 193, in do_task
    return func(**kw)
  File "pavement.py", line 40, in make
    git_branch_name = subprocess.check_output(["git", "rev-parse", "--abbrev-ref
", "HEAD"])
  File "E:\Programs\python\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "E:\Programs\python\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "E:\Programs\python\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

C:\Users\Brandon\Dropbox\tba git\the-blue-alliance>

**Comment by Almad** [comment]
My guess is that you don't have `git` in your `$PATH` on Windows. 

However, it looks like problem with your pavement, not with the paver itself.

If you'd still need further help, please post the relevant sections of your pavement file as well.
