### ISSUE TITLE
Rebuild documentation on pythonhosted.org and paver.github.io

### ISSUE THREAD

**Issue by singingwolfboy** [paver/paver#154]
The documentation at [pythonhosted.org](https://pythonhosted.org/Paver/) and [paver.github.io](https://paver.github.io/paver/) are outdated, and they need to be rebuilt and re-uploaded. Ideally, it would be better to use a post-commit hook on readthedocs.org and host the documentation there, instead.

**Comment by Almad** [comment]
Fair point, this part of intrastructure is kinda dated.

**Comment by pradyunsg** [comment]
You could deploy from Travis...

**Comment by Almad** [comment]
paver.github.io now redirects to RTD, and deploy from travis is set up, starting with next release.
