### ISSUE TITLE
virtualenv uses wrong script directory on windows

### ISSUE THREAD

**Issue by fkromer** [paver/paver#155]
**Reproduction**
I defined a task in *pavement.py* in the project root directory (which is not the OS installation partition C: but the data partition D:):

    from paver.tasks import task
    from paver.virtual import virtualenv
    from paver.easy import sh

    @task
    @virtualenv(dir="venv")
    def some_task():
        # something instead of pass
        pass

The virtual environment has been generated using `virtualenv venv` in the project root directory before executing the task and is located in \venv.

When i execute the task on Windows 10 (64 bit) over the command promt per `paver some_task` leads to the output of the following error message:

    FileNotFoundError: [Errno 2] No such file or directory: 'venv\\bin\\activate_this.py'
    D:\Users\Florian\Documents\GitHub\hamingja>paver tdd
    Traceback (most recent call last):
    File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\python34\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "C:\Python34\Scripts\paver.exe\__main__.py", line 9, in <module>
    File "c:\python34\lib\site-packages\paver\tasks.py", line 878, in main
      _launch_pavement(args)
    File "c:\python34\lib\site-packages\paver\tasks.py", line 858, in _launch_pavement
      _process_commands(args, auto_pending=auto_pending)
    File "c:\python34\lib\site-packages\paver\tasks.py", line 809, in _process_commands
      task()
    File "c:\python34\lib\site-packages\paver\tasks.py", line 317, in __call__
      with open(activate_this) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'venv\\bin\\activate_this.py'

The **activation script is located in 'venv\\Scripts\activate_this.py' on windows systems** instead of 'venv\\bin\\activate_this.py'.

When running the tests like described in README.txt locally on a Windows 10 (64 bit) system it seems like test `test_running_task_in_specified_virtualenv (tests_integration.test_virtualenv.TestVirtualenvTaskSpecification) ...` does never return. After waiting 5 minutes there is no output (neither "ok", nor "not ok").

**Possible bug cause**
[code passage in virtual.py, line 76 - 84](https://github.com/paver/paver/blob/master/paver/virtual.py)]

**Comment by Almad** [comment]
@fkromer Hi, sorry for the _late_ response -- do you think it would be possible for you to run the tests again on current master?

**Comment by fkromer** [comment]
I try to find some time the next days. (Thank you very much for this great package by the way.)

**Comment by fkromer** [comment]
With your current master the virtual environment (~ *venv\Scripts\activate_this.py*) is found and the task run successfully.

**Comment by Almad** [comment]
Thanks for the verification!
