### ISSUE TITLE
Paver 1.3

### ISSUE THREAD

**Issue by Almad** [paver/paver#162]
With Paver 1.3, I'd like to do few major changes:
- [x] With Jython 2.7 being finally released, discontinue support for Python < 2.7 and Jython < 2.7 and get rid of the ugly hacks
- [x] Support Python 3.5

For consideration / let's see how good will it be:
- [x] Do not vendor path/six/etc anymore and use usual dependency management instead while still allowing bootstrap

**Comment by Almad** [comment]
Before doing so, I'd like to clean up the bugtracker as much as possible and do one last 1.2 maintenance release for those who would be adversely affected by above.

**Comment by hugovk** [comment]
How about also dropping Python 3.2 and 3.3? Both are EOL.

Here's the pip installs for paver from PyPI for the last month, showing no 3.2 and virtually no 3.3:
```
$ pypinfo --percent --pip paver pyversion
python_version percent download_count
-------------- ------- --------------
2.7              79.3%          7,146
3.5               7.9%            710
3.6               7.6%            683
3.4               4.8%            433
3.3               0.3%             25
2.6               0.1%              5
3.7               0.0%              4

```

**Comment by hugovk** [comment]
PR https://github.com/paver/paver/pull/179 drops support for Python 2.6.

**Comment by Almad** [comment]
With some release problems, but 1.3 is out.
