### ISSUE TITLE
Paver install doesn't work / python-six issue

### ISSUE THREAD

**Issue by binary1230** [paver/paver#193]
i think related to #190

This is on a fresh ubuntu-14.04.05-LTS with Python3.4

```
# virtualenv env
..snip..

# env/bin/pip3 install paver
...snip...
Successfully installed paver-1.3.3

# env/bin/paver
Traceback (most recent call last):
  File "env/bin/paver", line 7, in <module>
    from paver.tasks import main
  File "/tmp/env/lib/python3.4/site-packages/paver/tasks.py", line 12, in <module>
    import six
ImportError: No module named 'six'
```

```
# dpkg --list | grep six
ii  python-six                         1.5.2-1ubuntu1                             all          Python 2 and 3 compatibility library (Python 2 interface)
ii  python-six-whl                     1.5.2-1ubuntu1                             all          Python 2 and 3 compatibility library (universal wheel)
ii  python3-six                        1.5.2-1ubuntu1                             all          Python 2 and 3 compatibility library (Python 3 interface)
```

**Comment by binary1230** [comment]
quick update, if I do:

```
# env/bin/pip3 install six
```

now it works.  I know this was changed in #180, just came as a bit of a breaking change for us, and either six isn't getting install automatically and it should, or the install instructions on github/website for paver don't seem to reflect that six is a dependency that has to be manually installed.

what's supposed to happen?

**Comment by Almad** [comment]
Weird, that worked for me when testing in dockerized ubuntu :(

Do you have any idea why it doesn’t obey install_requires?

**Comment by binary1230** [comment]
can try and look at it in a bit

**Comment by binary1230** [comment]
digging, 

it looks like it's an issue with setup.py and the minilib, on my box it seems to be failing to insert paver-minilib into the path and just calls the real tasks.py instead of the minilib one.

I think. disclaimer: not super familiar with packaging or paver guts

**Comment by binary1230** [comment]
one note, not sure if it matters but 'virtualenv' command doesn't copy any system packages in by default (like 'six'), so it might just happen to work for other folks using different commands like venv, if that's a thing.

**Comment by binary1230** [comment]
I'm also testing with pip's 'editable' feature like this now:

```cd paver && ../env/bin/pip3 install -e .```

**Comment by Almad** [comment]
...right, minilib generation may be an issue.

Does editable work?

(I am AFK now, but will look into it tomorrow as well)

**Comment by binary1230** [comment]
working theory:  I think the issue here is in setup.py, that the minilib load never happens because we have already imported paver.tasks from the non-minilib-version and it's cached.

Sequence:
1) We try and import paver.tasks
2) That import is successful, but importing six fails and throws an exception in tasks.py
3) Exception handler in setup.py runs which calls sys.path.insert(0, 'paver-minilib.zip')
4) import paver.tasks is called which we THINK should call into the minilib zipfile, but instead, uses the cached 'import paver.tasks' from before (the one that failed), and calls that again, and it again fails with a 'six' error.   We're never making it inside the zipfile

I think that the new thing that's not being handled is the fact that ImportError was designed to catch the situation where 'import paver.tasks' failed _because it doesn't exist_.  Now that it's failing _because of a new error inside it (six package doesn't exist)_, the code in setup.py isn't handling it.

To demo: This successfully loads the minilib (the lib itself and generation appears fine)
```
sys.path.insert(0, 'paver-minilib.zip')
import paver.tasks
```

----

So, I think the answer is to either somehow test if a module will exist without importing it (not sure that's possible) or to unload it (imp.reload() ?).   I'll see if I can cook up a sample that works.

**Comment by binary1230** [comment]
i am also AFK for a while but:

I think if you intentionally create an ImportError exception in tasks.py you will reproduce this behavior

**Comment by Almad** [comment]
That makes sense. Will try to reproduce and fix.

**Comment by Almad** [comment]
Opening #194 on that

**Comment by Almad** [comment]
@binary1230 Your thoughts on #195 would be welcome.

**Comment by binary1230** [comment]
Will have a look, super busy in next week with our event, will definitely
try and check it out.  I would say, don't wait up for me, and I can pin
paver to the older version in our setup for now so not blocked by it.

**Comment by binary1230** [comment]
just quick comment on this:  latest (1.3.4) appears to fix this.  thanks so much!

**Comment by Almad** [comment]
Good, thanks for the verification! :)
