### ISSUE TITLE
The official website on github headline is dead

### ISSUE THREAD

**Issue by shelling** [paver/paver#196]
<img width="764" alt="screen shot 2018-01-04 at 1 53 45 pm" src="https://user-images.githubusercontent.com/4980/34585935-b6ac3914-f156-11e7-98fc-9bdf27e93edb.png">

**Comment by Almad** [comment]
Wow, had no idea trailing slash got encoded, rendering the link unusable. Fixed, thanks!

(note that this will change anyway because of #167 )
