### ISSUE TITLE
Remove unnecessary external modules

### ISSUE THREAD

**Issue by mcepl** [paver/paver#206]
* nose: it is actually not needed at all: paver uses only `SkipTest` exception, which is also present in the standard library in the `unittest` module.

* mock and virtualenv: these are unnecessary as well, because since 3.3 they are part of the standard library (perhaps that’s the solution for #205 as well?).

This [patch](https://github.com/paver/paver/files/5651240/remove_external_pkgs.patch.txt) resolves all three problems.

**Comment by Almad** [comment]
Thanks!

I'll try to find some time to wrap-up the next release that will drop Python 2.x. I think this will not resolve #205 though for people who want to use the newest virtualenv, but let me try.

**Comment by mcepl** [comment]
[Updated version of the patch](https://github.com/paver/paver/files/5685457/remove_external_pkgs.patch.txt) (works even with Python 2.* and external mock).

**Comment by Almad** [comment]
Thanks!
