### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [paver/paver#213]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine paver/tests/utils.py and observe `interupting`, however expect to see `interrupting`.
- Examine docs/source/pavement.rst and observe `fullfilled`, however expect to see `fulfilled`.
- Examine paver/shell.py and observe `exectuting`, however expect to see `executing`.
- Examine paver/tests/test_tasks.py and observe `enougth`, however expect to see `enough`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/paver/pull/new/bugfix_typos

Thanks.

**Comment by Almad** [comment]
Thanks @timgates42
