### ISSUE TITLE
Does not work with multiprocessing on Windows

### ISSUE THREAD

**Issue by mkorpela** [paver/paver#80]
Hi all!

Yesterday I started prototyping the use of multiprocessing in the project ( https://github.com/robotframework/RIDE ) that I'm working on.
Everything went well until I executed our application on Windows.. Suddenly I had multiple applications!?!! and executing our unit tests through paver also got me in to a situation where the testing never ends.

So how is this related to paver:
Multiprocessing has a very odd requirement that the entry point (in our case paver start script) must be safe to import when creating a new process. http://docs.python.org/library/multiprocessing.html#windows

So there must be this block in the start script:
if **name** == '**main**':
     do_the_starting()

And it seems that paver has not this in place (nor does our basic start script - this I can fix by myself).

Nosetests has a workaround for this issue: 
https://github.com/nose-devs/nose/blob/master/setup.py [starting from line 43] but I'm unsure how to implement the same thing in paver..

**Comment by kn-neeraj** [comment]
any solution to this?

**Comment by mkorpela** [comment]
@kn-neeraj I think this is not the issue you are looking for. I’ll close this issue as it is from year 2012 and paver developers have not closed it. Most likely multiprocessing and windows are now different.

**Comment by kn-neeraj** [comment]
Hi @mkorpela 
I was trying to run a sample app which uses Paver and multiprocessing. Its not running on windows so I guess its facing the same issue you raised long back. Do you have a workaround for this?

**Comment by Almad** [comment]
@mkorpela I haven't closed it since I thought it may still be relevant, but had no way to verify without windows :)

**Comment by Almad** [comment]
@kn-neeraj could you please describe your problem in detail? If you are not running on windows, maybe please open a new issue (also so we don't spam the original author), let's take a look at it!
